import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Quill & Compass",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-qc-parchment p-4">
      <div className="w-full max-w-3xl space-y-8 py-12">
        <header className="text-center space-y-2">
          <h1 className="font-display text-4xl text-qc-charcoal">
            Terms of Service
          </h1>
          <p className="font-body text-sm text-qc-text-muted">
            Effective Date: March 30, 2026 &middot; Last Updated: March 30, 2026
          </p>
        </header>

        {/* ── Plain-Language Summary (HON-16: ≤8th-grade reading level) ── */}
        <section className="rounded-qc-md border border-qc-primary/20 bg-qc-primary/5 p-6 space-y-4">
          <h2 className="font-display text-xl text-qc-charcoal">
            Summary — Plain Language
          </h2>
          <div className="qc-prose font-body text-qc-charcoal space-y-3 text-sm leading-relaxed">
            <p>
              <strong>Your data belongs to you.</strong> Everything you create in
              QuillNext — courses, journals, transcripts — is yours. You can
              export it at any time and delete your account whenever you want.
            </p>
            <p>
              <strong>We may change the service.</strong> We may add features,
              fix bugs, or update the interface. If we make a big change that
              removes a feature or changes how things work, we will let you know
              by email before it happens and give you time to export your data.
            </p>
            <p>
              <strong>You can leave at any time.</strong> There are no contracts
              or penalties. Delete your account and all your data is permanently
              removed within 30 days.
            </p>
            <p>
              <strong>If we shut down:</strong> We will give you at least 90
              days notice, keep the export feature running, and email you
              instructions to download all your data before the service ends.
            </p>
          </div>
        </section>

        {/* ── Full Terms of Service ── */}
        <article className="qc-prose font-body text-qc-charcoal space-y-6 text-sm leading-relaxed">
          <h2 className="font-display text-2xl">1. Acceptance of Terms</h2>
          <p>
            By creating an account or using QuillNext (&ldquo;the
            Service&rdquo;), operated by Quill &amp; Compass
            (&ldquo;we&rdquo;, &ldquo;us&rdquo;), you agree to these Terms of
            Service. If you do not agree, do not use the Service.
          </p>

          <h2 className="font-display text-2xl">2. Description of Service</h2>
          <p>
            QuillNext is a web-based curriculum management and family
            discipleship platform for homeschool families. The Service requires
            an active internet connection for all features. QuillNext uses AI
            (Google Gemini) to generate personalized educational content.
          </p>

          <h2 className="font-display text-2xl">3. Your Account</h2>
          <p>
            You sign in using Google OAuth. You are responsible for the
            security of your Google account. You must be at least 18 years old
            to create an account. Student profiles are created and managed by
            the parent account holder.
          </p>

          <h2 className="font-display text-2xl">4. Your Content &amp; Data Rights</h2>
          <p>
            You own all content you create within QuillNext. We do not claim
            ownership of your courses, journals, transcripts, or any other
            user-generated content. You grant us a limited license to store,
            display, and process your content solely to provide the Service.
          </p>
          <p>You have the right to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              <strong>Export</strong> all your data in JSON format at any time.
            </li>
            <li>
              <strong>Delete</strong> your account and all associated data
              permanently.
            </li>
            <li>
              <strong>Deactivate</strong> your account temporarily while
              preserving your data.
            </li>
          </ul>

          <h2 className="font-display text-2xl">5. AI-Generated Content</h2>
          <p>
            Content generated by AI (curriculum, lessons, quizzes) is produced
            by Google Gemini based on context you provide. AI-generated content
            is labeled as such within the application. You are responsible for
            reviewing AI-generated content before using it with your students.
            We do not guarantee the accuracy or appropriateness of AI-generated
            content.
          </p>

          <h2 className="font-display text-2xl">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to access other users&apos; accounts or data</li>
            <li>Interfere with the operation of the Service</li>
            <li>Use the Service to generate harmful or illegal content</li>
          </ul>

          <h2 className="font-display text-2xl">7. Service Changes</h2>
          <p>
            We may modify, update, or discontinue features of the Service. For
            material changes that remove features or substantially change
            functionality:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>We will notify you by email at least 30 days in advance.</li>
            <li>We will provide a summary of what changed.</li>
            <li>Your data export will remain available throughout any transition.</li>
          </ul>

          <h2 className="font-display text-2xl">8. Service Discontinuation</h2>
          <p>
            If we decide to shut down QuillNext, we commit to:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Providing at least 90 days advance notice via email.
            </li>
            <li>
              Keeping the data export feature operational throughout the
              notice period.
            </li>
            <li>
              Emailing all users with instructions to download their data.
            </li>
            <li>
              Permanently destroying all remaining user data within 30 days
              after the service ends.
            </li>
          </ul>

          <h2 className="font-display text-2xl">9. Limitation of Liability</h2>
          <p>
            QuillNext is provided &ldquo;as is&rdquo; without warranties of
            any kind. We are not liable for any damages arising from your use
            of the Service, including but not limited to loss of data, errors
            in AI-generated content, or service interruptions. Our total
            liability is limited to the amount you have paid us in the 12
            months preceding the claim (currently $0 as the Service is free).
          </p>

          <h2 className="font-display text-2xl">10. Cancellation</h2>
          <p>
            You may stop using QuillNext at any time. You can delete your
            account from Account Settings &rarr; Data &amp; Privacy. There are
            no cancellation fees, penalties, or retention requirements. Upon
            deletion, all your data is permanently destroyed within 30 days.
          </p>

          <h2 className="font-display text-2xl">
            11. Changes to These Terms
          </h2>
          <p>
            We may update these Terms. For material changes, we will notify you
            by email before the new terms take effect and provide a summary of
            changes. Continued use after the effective date constitutes
            acceptance. If you disagree, you may export your data and delete
            your account.
          </p>

          <h2 className="font-display text-2xl">12. Contact</h2>
          <p>
            Questions about these Terms? Contact us at{" "}
            <a
              href="mailto:adam@quillandcompass.app"
              className="underline text-qc-primary hover:text-qc-primary/80"
            >
              adam@quillandcompass.app
            </a>
            .
          </p>
        </article>

        <footer className="text-center pt-8 border-t border-qc-border-subtle">
          <Link
            href="/"
            className="font-body text-sm text-qc-primary hover:underline"
          >
            &larr; Back to QuillNext
          </Link>
        </footer>
      </div>
    </div>
  );
}
